openapi: 3.0.3

paths: {}

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc Universal API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

tags:
  - name: Common schemas
    description: Common schemas that can be resued

components:
  schemas:
    merchantSummary:
      type: object
      title: merchant summary
      description: Object that contains information about the merchant.
      properties:
        merchantId:
          type: string
          description: Unique identifier of the merchant.
          example: '4525644354'
        doingBusinessAs:
          type: string
          description: Legal name that the business operates as.
          example: Doe Hot Dogs
        link:
          $ref: '../common/link/link-v1.yaml#/components/schemas/link'
      example:
        merchantId: '4525644354'
        doingBusinessAs: Doe Hot Dogs
        link: 
          rel: merchant
          method: get
          href: 'https://api.payroc.com/v1/merchants/4525644354'
