openapi: 3.0.3

paths: {}

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

tags:
  - name: Common schemas
    description: Common schemas that can be resued

components:
  schemas:
    legalAddress:
      title: Legal address
      required:
      - type
      - city
      - country
      - address1
      - postalCode
      - state
      allOf:
        - type: object
          properties:
            type:
              type: string
              description: Type of address
              enum:
                - "legalAddress"
              default: "legalAddress"
        - $ref: '../common/address-v1.yaml#/components/schemas/address'
